// Sample: Detail Page — PAGE-02
// Generated by fresh-context subagent reading only rule files.
// Rules applied: components.md, cards.md, tokens.md, formatting.md,
//                data-table.md, page-templates.md

import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardAction,
} from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { ChartContainer } from "@/components/ui/chart"
import { ArrowLeftIcon } from "lucide-react"
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
} from "recharts"
import { DataTable, KpiCard } from "@/components/composed"
import {
  formatCurrencyCompact,
  formatCompact,
  formatDelta,
  formatCurrency,
  formatNumber,
  formatPercent,
} from "@/lib/format"

// --- Mock data ---

const campaign = {
  name: "Summer Promo 2026",
  status: "active",
}

const locale = "en-US" as const
const currency = "USD" as const

const kpiItems = [
  { label: "Total Spend", value: formatCurrencyCompact(4320, { locale, currency }), delta: formatDelta(0.12), deltaPositive: true },
  { label: "Impressions", value: formatCompact(120000, { locale }), delta: formatDelta(0.08), deltaPositive: true },
  { label: "Clicks", value: formatCompact(3400, { locale }), delta: formatDelta(0.05), deltaPositive: true },
  { label: "CTR", value: formatPercent(0.0283, { locale }), delta: formatDelta(-0.003), deltaPositive: false },
]

const spendData = [
  { date: "Mar 1", spend: 180 },
  { date: "Mar 8", spend: 220 },
  { date: "Mar 15", spend: 310 },
  { date: "Mar 22", spend: 280 },
  { date: "Mar 29", spend: 390 },
  { date: "Apr 5", spend: 450 },
  { date: "Apr 12", spend: 410 },
]

const impressionData = [
  { date: "Mar 1", impressions: 14000 },
  { date: "Mar 8", impressions: 18200 },
  { date: "Mar 15", impressions: 21500 },
  { date: "Mar 22", impressions: 19800 },
  { date: "Mar 29", impressions: 24300 },
  { date: "Apr 5", impressions: 27000 },
  { date: "Apr 12", impressions: 25200 },
]

const spendChartConfig = {
  spend: { label: "Spend", color: "var(--chart-1)" },
}

const impressionChartConfig = {
  impressions: { label: "Impressions", color: "var(--chart-2)" },
}

type AdGroup = {
  id: string
  name: string
  status: string
  spend: number
  impressions: number
  clicks: number
  ctr: number
  cpc: number
}

const adGroups: AdGroup[] = [
  { id: "1", name: "Prospecting - Age 25-34", status: "active", spend: 1200, impressions: 38000, clicks: 1100, ctr: 0.0289, cpc: 1.09 },
  { id: "2", name: "Retargeting - Cart Abandoners", status: "active", spend: 980, impressions: 22500, clicks: 870, ctr: 0.0387, cpc: 1.13 },
  { id: "3", name: "Lookalike - Top Buyers", status: "paused", spend: 740, impressions: 31000, clicks: 680, ctr: 0.0219, cpc: 1.09 },
  { id: "4", name: "Brand Search", status: "active", spend: 1400, impressions: 28500, clicks: 750, ctr: 0.0263, cpc: 1.87 },
]

const adGroupColumns = [
  {
    accessorKey: "name" as keyof AdGroup,
    header: "Ad Group",
    pinned: "left" as const,
    sortable: true,
    cell: (row: AdGroup) => (
      <span className="font-medium text-foreground">{row.name}</span>
    ),
  },
  {
    accessorKey: "status" as keyof AdGroup,
    header: "Status",
    sortable: true,
    cell: (row: AdGroup) => <Badge variant="outline">{row.status}</Badge>,
  },
  {
    accessorKey: "spend" as keyof AdGroup,
    header: "Spend",
    sortable: true,
    align: "right" as const,
    cell: (row: AdGroup) => (
      <span className="tabular-nums font-medium">{formatCurrency(row.spend, { locale, currency })}</span>
    ),
  },
  {
    accessorKey: "impressions" as keyof AdGroup,
    header: "Impressions",
    sortable: true,
    align: "right" as const,
    cell: (row: AdGroup) => (
      <span className="tabular-nums">{formatNumber(row.impressions, { locale })}</span>
    ),
  },
  {
    accessorKey: "clicks" as keyof AdGroup,
    header: "Clicks",
    sortable: true,
    align: "right" as const,
    cell: (row: AdGroup) => (
      <span className="tabular-nums">{formatNumber(row.clicks, { locale })}</span>
    ),
  },
  {
    accessorKey: "ctr" as keyof AdGroup,
    header: "CTR",
    sortable: true,
    align: "right" as const,
    cell: (row: AdGroup) => (
      <span className="tabular-nums">{formatPercent(row.ctr, { locale })}</span>
    ),
  },
  {
    accessorKey: "cpc" as keyof AdGroup,
    header: "CPC",
    sortable: true,
    align: "right" as const,
    cell: (row: AdGroup) => (
      <span className="tabular-nums">{formatCurrency(row.cpc, { locale, currency })}</span>
    ),
  },
]

export default function CampaignDetailPage() {
  const navigate = (path: string) => {
    console.log("Navigate to:", path)
  }

  return (
    <div className="flex flex-col gap-6 p-6">
      {/* Page Header -- div, not Card. Back button + status badge. */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => navigate("/campaigns")}>
            <ArrowLeftIcon className="h-4 w-4" />
          </Button>
          <div>
            <h1 className="text-2xl font-semibold">{campaign.name}</h1>
            <p className="text-sm text-muted-foreground">Campaign details and performance</p>
          </div>
        </div>
        <Badge variant="outline">{campaign.status}</Badge>
      </div>

      {/* KPI Cards -- 4-column responsive grid */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
        {kpiItems.map((item) => (
          <KpiCard
            key={item.label}
            label={item.label}
            value={item.value}
            delta={item.delta}
            deltaPositive={item.deltaPositive}
          />
        ))}
      </div>

      {/* Chart Cards -- 2-column grid */}
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Daily Spend</CardTitle>
            <CardDescription>Last 7 weeks of ad spend</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer config={spendChartConfig}>
              <LineChart data={spendData}>
                <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" />
                <XAxis
                  dataKey="date"
                  stroke="var(--muted-foreground)"
                  tick={{ fontSize: 12, fill: "var(--muted-foreground)" }}
                />
                <YAxis
                  stroke="var(--muted-foreground)"
                  tick={{ fontSize: 12, fill: "var(--muted-foreground)" }}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "var(--card)",
                    borderColor: "var(--border)",
                    color: "var(--card-foreground)",
                  }}
                />
                <Line
                  type="monotone"
                  dataKey="spend"
                  stroke="var(--chart-1)"
                  strokeWidth={2}
                  dot={false}
                />
              </LineChart>
            </ChartContainer>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Impressions</CardTitle>
            <CardDescription>Weekly impression volume</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer config={impressionChartConfig}>
              <BarChart data={impressionData}>
                <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" />
                <XAxis
                  dataKey="date"
                  stroke="var(--muted-foreground)"
                  tick={{ fontSize: 12, fill: "var(--muted-foreground)" }}
                />
                <YAxis
                  stroke="var(--muted-foreground)"
                  tick={{ fontSize: 12, fill: "var(--muted-foreground)" }}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "var(--card)",
                    borderColor: "var(--border)",
                    color: "var(--card-foreground)",
                  }}
                />
                <Bar dataKey="impressions" fill="var(--chart-2)" />
              </BarChart>
            </ChartContainer>
          </CardContent>
        </Card>
      </div>

      {/* Related Table Card */}
      <Card>
        <CardHeader>
          <CardTitle>Ad Groups</CardTitle>
          <CardDescription>Linked ad groups for this campaign</CardDescription>
        </CardHeader>
        <CardContent>
          <DataTable
            columns={adGroupColumns}
            data={adGroups}
            onRowClick={(row) => navigate(`/ad-groups/${row.id}`)}
            emptyMessage="No ad groups found."
          />
        </CardContent>
      </Card>
    </div>
  )
}
