// Sample: Detail Page — PAGE-02
// Generated by fresh-context subagent reading only rule files.
// Rules applied: components.md, component-interfaces.md, tokens.md, forbidden.md,
//                forms.md, naming.md, page-templates.md

import {
  PageLayout,
  PageHeader,
  KpiCardGroup,
  ChartSection,
  DataTable,
  StatusBadge,
  ActionButton,
} from "@/components/composed"
import React from "react"
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts"

type AdGroup = {
  id: string
  name: string
  status: "active" | "paused" | "ended"
  spend: string
  impressions: string
  clicks: string
  ctr: string
  cpc: string
}

const kpiItems = [
  { label: "Total Spend", value: "$4,320", delta: "+12%", deltaPositive: true },
  { label: "Impressions", value: "120,000", delta: "+8%", deltaPositive: true },
  { label: "Clicks", value: "3,400", delta: "+5%", deltaPositive: true },
  { label: "CTR", value: "2.83%", delta: "-0.3%", deltaPositive: false },
]

const spendData = [
  { date: "Mar 1", spend: 180 },
  { date: "Mar 8", spend: 220 },
  { date: "Mar 15", spend: 310 },
  { date: "Mar 22", spend: 280 },
  { date: "Mar 29", spend: 390 },
  { date: "Apr 5", spend: 450 },
  { date: "Apr 12", spend: 410 },
]

function SpendLineChart() {
  return (
    <ResponsiveContainer width="100%" height={240}>
      <LineChart data={spendData}>
        <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" />
        <XAxis dataKey="date" stroke="var(--muted-foreground)" tick={{ fontSize: 12, fill: "var(--muted-foreground)" }} />
        <YAxis stroke="var(--muted-foreground)" tick={{ fontSize: 12, fill: "var(--muted-foreground)" }} />
        <Tooltip
          contentStyle={{
            backgroundColor: "var(--card)",
            borderColor: "var(--border)",
            color: "var(--card-foreground)",
          }}
        />
        <Line type="monotone" dataKey="spend" stroke="var(--chart-1)" strokeWidth={2} dot={false} />
      </LineChart>
    </ResponsiveContainer>
  )
}

const adGroups: AdGroup[] = [
  { id: "1", name: "Prospecting - Age 25-34", status: "active", spend: "$1,200", impressions: "38,000", clicks: "1,100", ctr: "2.89%", cpc: "$1.09" },
  { id: "2", name: "Retargeting - Cart Abandoners", status: "active", spend: "$980", impressions: "22,500", clicks: "870", ctr: "3.87%", cpc: "$1.13" },
  { id: "3", name: "Lookalike - Top Buyers", status: "paused", spend: "$740", impressions: "31,000", clicks: "680", ctr: "2.19%", cpc: "$1.09" },
  { id: "4", name: "Brand Search", status: "active", spend: "$1,400", impressions: "28,500", clicks: "750", ctr: "2.63%", cpc: "$1.87" },
]

const adGroupColumns = [
  { key: "name" as keyof AdGroup, header: "Ad Group", sortable: true },
  {
    key: "status" as keyof AdGroup,
    header: "Status",
    render: (value: AdGroup[keyof AdGroup]) => (
      <StatusBadge status={value as string} />
    ),
  },
  { key: "spend" as keyof AdGroup, header: "Spend", sortable: true },
  { key: "impressions" as keyof AdGroup, header: "Impressions", sortable: true },
  { key: "clicks" as keyof AdGroup, header: "Clicks", sortable: true },
  { key: "ctr" as keyof AdGroup, header: "CTR", sortable: true },
  { key: "cpc" as keyof AdGroup, header: "CPC", sortable: true },
]

export default function CampaignDetailPage() {
  const handleAdGroupClick = (row: AdGroup) => {
    console.log("Navigate to ad group:", row.id)
  }

  const handleEdit = () => {
    console.log("Edit campaign")
  }

  return (
    <PageLayout>
      <PageHeader
        title="Summer Promo 2026"
        backHref="/campaigns"
        action={<StatusBadge status="active" />}
      />
      <KpiCardGroup cols={4} items={kpiItems} />
      <ChartSection
        cols={1}
        charts={[{ title: "Daily Spend", chart: <SpendLineChart /> }]}
      />
      <DataTable
        columns={adGroupColumns}
        data={adGroups}
        onRowClick={handleAdGroupClick}
        actions={<ActionButton onClick={handleEdit}>Edit Campaign</ActionButton>}
        emptyMessage="No ad groups found."
      />
    </PageLayout>
  )
}
