// Sample: Form / Settings Page — PAGE-03
// Generated by fresh-context subagent reading only rule files.
// Rules applied: components.md, component-interfaces.md, tokens.md, forbidden.md,
//                forms.md, naming.md, page-templates.md

import {
  PageLayout,
  PageHeader,
  FormFieldSet,
  FormRow,
  FormField,
  FormActions,
  ActionButton,
  Input,
  Select,
  Textarea,
  DateRangePicker,
} from "@/components/composed"

const statusOptions = [
  { label: "Draft", value: "draft" },
  { label: "Active", value: "active" },
  { label: "Paused", value: "paused" },
]

const objectiveOptions = [
  { label: "Brand Awareness", value: "awareness" },
  { label: "Lead Generation", value: "leads" },
  { label: "Conversions", value: "conversions" },
  { label: "Traffic", value: "traffic" },
]

const channelOptions = [
  { label: "Search", value: "search" },
  { label: "Display", value: "display" },
  { label: "Social", value: "social" },
  { label: "Video", value: "video" },
]

const regionOptions = [
  { label: "Global", value: "global" },
  { label: "North America", value: "na" },
  { label: "Europe", value: "eu" },
  { label: "Asia Pacific", value: "apac" },
]

export default function CampaignFormPage() {
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    console.log("Form submitted")
  }

  const handleCancel = () => {
    console.log("Cancel — navigate back to /campaigns")
  }

  return (
    <PageLayout>
      <PageHeader title="Create Campaign" backHref="/campaigns" />
      <form onSubmit={handleSubmit}>
        <FormFieldSet legend="Basic Info">
          <FormRow cols={2}>
            <FormField label="Campaign Name" required>
              <Input name="name" placeholder="Enter campaign name" />
            </FormField>
            <FormField label="Status">
              <Select name="status" options={statusOptions} />
            </FormField>
          </FormRow>
          <FormRow cols={2}>
            <FormField label="Objective" required>
              <Select name="objective" options={objectiveOptions} />
            </FormField>
            <FormField label="Channel" required>
              <Select name="channel" options={channelOptions} />
            </FormField>
          </FormRow>
          <FormField label="Description" description="Optional — describe the campaign goal">
            <Textarea name="description" placeholder="Enter a short description..." />
          </FormField>
        </FormFieldSet>

        <FormFieldSet legend="Budget & Schedule">
          <FormRow cols={2}>
            <FormField label="Total Budget" required description="Maximum lifetime spend in USD">
              <Input name="budget" placeholder="e.g. 10000" />
            </FormField>
            <FormField label="Daily Cap" description="Maximum daily spend in USD">
              <Input name="dailyCap" placeholder="e.g. 500" />
            </FormField>
          </FormRow>
          <FormRow cols={2}>
            <FormField label="Flight Dates" required>
              <DateRangePicker name="flightDates" />
            </FormField>
            <FormField label="Target Region">
              <Select name="region" options={regionOptions} />
            </FormField>
          </FormRow>
        </FormFieldSet>

        <FormActions>
          <ActionButton variant="outline" onClick={handleCancel}>Cancel</ActionButton>
          <ActionButton type="submit">Save</ActionButton>
        </FormActions>
      </form>
    </PageLayout>
  )
}
