// Sample: List Page — PAGE-01
// Generated by fresh-context subagent reading only rule files.
// Rules applied: components.md, component-interfaces.md, tokens.md, forbidden.md,
//                forms.md, naming.md, page-templates.md

import {
  PageLayout,
  PageHeader,
  SearchBar,
  DataTable,
  ActionButton,
  StatusBadge,
} from "@/components/composed"

type Campaign = {
  id: string
  name: string
  status: "active" | "paused" | "ended" | "draft"
  budget: string
  spend: string
  impressions: string
  clicks: string
  startDate: string
}

const mockCampaigns: Campaign[] = [
  { id: "1", name: "Summer Promo 2026", status: "active", budget: "$10,000", spend: "$4,320", impressions: "120,000", clicks: "3,400", startDate: "2026-06-01" },
  { id: "2", name: "Brand Awareness Q2", status: "active", budget: "$8,500", spend: "$2,100", impressions: "98,000", clicks: "1,800", startDate: "2026-04-15" },
  { id: "3", name: "Retargeting - Spring", status: "paused", budget: "$5,000", spend: "$3,800", impressions: "75,000", clicks: "2,200", startDate: "2026-03-01" },
  { id: "4", name: "Product Launch - Model X", status: "ended", budget: "$15,000", spend: "$15,000", impressions: "310,000", clicks: "9,100", startDate: "2026-01-10" },
  { id: "5", name: "Holiday Campaign 2025", status: "ended", budget: "$12,000", spend: "$11,450", impressions: "280,000", clicks: "7,800", startDate: "2025-11-25" },
  { id: "6", name: "Influencer Collab - Spring", status: "draft", budget: "$6,000", spend: "$0", impressions: "0", clicks: "0", startDate: "2026-05-01" },
  { id: "7", name: "Search - Brand Terms", status: "active", budget: "$3,000", spend: "$1,200", impressions: "45,000", clicks: "4,500", startDate: "2026-02-20" },
]

const statusOptions = [
  { label: "All", value: "" },
  { label: "Active", value: "active" },
  { label: "Paused", value: "paused" },
  { label: "Ended", value: "ended" },
  { label: "Draft", value: "draft" },
]

const columns = [
  { key: "name" as keyof Campaign, header: "Campaign Name", sortable: true },
  {
    key: "status" as keyof Campaign,
    header: "Status",
    render: (value: Campaign[keyof Campaign]) => (
      <StatusBadge status={value as string} />
    ),
  },
  { key: "budget" as keyof Campaign, header: "Budget", sortable: true },
  { key: "spend" as keyof Campaign, header: "Spend", sortable: true },
  { key: "impressions" as keyof Campaign, header: "Impressions", sortable: true },
  { key: "clicks" as keyof Campaign, header: "Clicks", sortable: true },
  { key: "startDate" as keyof Campaign, header: "Start Date", sortable: true },
]

export default function CampaignListPage() {
  const handleSearch = (values: Record<string, unknown>) => {
    console.log("Search:", values)
  }

  const handleRowClick = (row: Campaign) => {
    console.log("Navigate to campaign:", row.id)
  }

  const handleCreate = () => {
    console.log("Create new campaign")
  }

  return (
    <PageLayout>
      <PageHeader
        title="Campaigns"
        subtitle={`${mockCampaigns.length} campaigns`}
        action={<ActionButton onClick={handleCreate}>New Campaign</ActionButton>}
      />
      <SearchBar
        filters={[
          { type: "text", key: "name", label: "Campaign Name" },
          { type: "select", key: "status", label: "Status", options: statusOptions },
          { type: "daterange", key: "dateRange", label: "Date Range" },
        ]}
        onSearch={handleSearch}
      />
      <DataTable
        columns={columns}
        data={mockCampaigns}
        onRowClick={handleRowClick}
        emptyMessage="No campaigns found."
      />
    </PageLayout>
  )
}
