// Sample: Dashboard Overview Page — PAGE-04
// Generated by fresh-context subagent reading only rule files.
// Rules applied: components.md, component-interfaces.md, tokens.md, forbidden.md,
//                forms.md, naming.md, page-templates.md

import {
  PageLayout,
  PageHeader,
  KpiCardGroup,
  ChartSection,
  DataTable,
  ActionButton,
  StatusBadge,
} from "@/components/composed"
import React from "react"
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from "recharts"

// KPI mock data
const kpiItems = [
  { label: "Total Spend", value: "$42,800", delta: "+18%", deltaPositive: true },
  { label: "Total Impressions", value: "1.24M", delta: "+23%", deltaPositive: true },
  { label: "Total Clicks", value: "38,400", delta: "+11%", deltaPositive: true },
  { label: "Avg CTR", value: "3.09%", delta: "-0.2%", deltaPositive: false },
]

// Chart mock data
const dailySpendData = [
  { date: "Mar 1", spend: 1200 },
  { date: "Mar 8", spend: 1450 },
  { date: "Mar 15", spend: 1600 },
  { date: "Mar 22", spend: 1350 },
  { date: "Mar 29", spend: 1800 },
  { date: "Apr 5", spend: 2100 },
  { date: "Apr 12", spend: 1950 },
]

const channelSplitData = [
  { channel: "Search", spend: 18200, impressions: 520000 },
  { channel: "Display", spend: 9400, impressions: 380000 },
  { channel: "Social", spend: 11600, impressions: 210000 },
  { channel: "Video", spend: 3600, impressions: 130000 },
]

function DailySpendChart() {
  return (
    <ResponsiveContainer width="100%" height={240}>
      <LineChart data={dailySpendData}>
        <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" />
        <XAxis dataKey="date" stroke="var(--muted-foreground)" tick={{ fontSize: 12, fill: "var(--muted-foreground)" }} />
        <YAxis stroke="var(--muted-foreground)" tick={{ fontSize: 12, fill: "var(--muted-foreground)" }} />
        <Tooltip
          contentStyle={{
            backgroundColor: "var(--card)",
            borderColor: "var(--border)",
            color: "var(--card-foreground)",
          }}
        />
        <Line type="monotone" dataKey="spend" stroke="var(--chart-1)" strokeWidth={2} dot={false} />
      </LineChart>
    </ResponsiveContainer>
  )
}

function ChannelSplitChart() {
  return (
    <ResponsiveContainer width="100%" height={240}>
      <BarChart data={channelSplitData}>
        <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" />
        <XAxis dataKey="channel" stroke="var(--muted-foreground)" tick={{ fontSize: 12, fill: "var(--muted-foreground)" }} />
        <YAxis stroke="var(--muted-foreground)" tick={{ fontSize: 12, fill: "var(--muted-foreground)" }} />
        <Tooltip
          contentStyle={{
            backgroundColor: "var(--card)",
            borderColor: "var(--border)",
            color: "var(--card-foreground)",
          }}
        />
        <Legend wrapperStyle={{ fontSize: 12, color: "var(--muted-foreground)" }} />
        <Bar dataKey="spend" fill="var(--chart-2)" name="Spend ($)" />
      </BarChart>
    </ResponsiveContainer>
  )
}

// Recent campaigns table mock data
type RecentCampaign = {
  id: string
  name: string
  status: "active" | "paused" | "ended" | "draft"
  spend: string
  impressions: string
  ctr: string
}

const recentCampaigns: RecentCampaign[] = [
  { id: "1", name: "Summer Promo 2026", status: "active", spend: "$4,320", impressions: "120,000", ctr: "2.83%" },
  { id: "2", name: "Brand Awareness Q2", status: "active", spend: "$2,100", impressions: "98,000", ctr: "1.84%" },
  { id: "3", name: "Retargeting - Spring", status: "paused", spend: "$3,800", impressions: "75,000", ctr: "2.93%" },
  { id: "4", name: "Product Launch - Model X", status: "ended", spend: "$15,000", impressions: "310,000", ctr: "2.94%" },
  { id: "5", name: "Influencer Collab - Spring", status: "draft", spend: "$0", impressions: "0", ctr: "—" },
]

const campaignColumns = [
  { key: "name" as keyof RecentCampaign, header: "Campaign", sortable: true },
  {
    key: "status" as keyof RecentCampaign,
    header: "Status",
    render: (value: RecentCampaign[keyof RecentCampaign]) => (
      <StatusBadge status={value as string} />
    ),
  },
  { key: "spend" as keyof RecentCampaign, header: "Spend", sortable: true },
  { key: "impressions" as keyof RecentCampaign, header: "Impressions", sortable: true },
  { key: "ctr" as keyof RecentCampaign, header: "CTR", sortable: true },
]

export default function DashboardOverviewPage() {
  const handleRowClick = (row: RecentCampaign) => {
    console.log("Navigate to campaign:", row.id)
  }

  const handleNewCampaign = () => {
    console.log("Create new campaign")
  }

  return (
    <PageLayout>
      <PageHeader
        title="Dashboard"
        subtitle="Overview of marketing performance"
        action={<ActionButton onClick={handleNewCampaign}>New Campaign</ActionButton>}
      />
      <KpiCardGroup
        cols={4}
        items={kpiItems}
      />
      <ChartSection
        cols={2}
        charts={[
          { title: "Daily Spend", chart: <DailySpendChart /> },
          { title: "Channel Split", chart: <ChannelSplitChart /> },
        ]}
      />
      <DataTable
        columns={campaignColumns}
        data={recentCampaigns}
        onRowClick={handleRowClick}
        emptyMessage="No recent campaigns."
      />
    </PageLayout>
  )
}
